services:
  web:
    build: ./docker
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8090:80
      - 5173:5173 #for vite
    working_dir: ${APP_PATH_CONTAINER}
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3316}:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
